name: build-workflow

on: 
  workflow_call

jobs:
  build-app:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout my github project
        uses: actions/checkout@v3

      - name: Build project
        run: go build -v math.go

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.0
        with:
          name: programa-go-${{ github.ref_name }}
          path: math