name: ci-golang-dev-workflow

on: 
  push:
    branches: 
      - develop
      - main

jobs:
  ci-build:
    needs: ci-sonarcloud
    uses: ./.github/workflows/build.yaml
    secrets: inherit

  ci-docker:
    needs: ci-build
    uses: ./.github/workflows/docker.yaml
    secrets: inherit