name: ci-golang-workflow

on: 
  push:
    branches:
      - '*'
      - '!develop'
      - '!main'
  pull_request:
    branches:
      - '*'

jobs:
  ci-test:
    uses: ./.github/workflows/testes.yaml
    secrets: inherit

  ci-sonarcloud:
    uses: ./.github/workflows/sonarcloud.yaml
    secrets: inherit
