name: ci-golang-workflow

on: 
  push:
    branches:
      - develop
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  ci-test:
    uses: ./.github/workflows/testes.yaml
    secrets: inherit

  ci-sonarcloud:
    needs: ci-test
    uses: ./.github/workflows/sonarcloud.yaml
    secrets: inherit
